### ISSUE TITLE
zazu dev start from default or configured branch

### ISSUE THREAD

**Issue by moorepatrick** [stopthatcow/zazu#102]
It would be helpful to use the default branch set in github (or one stored in .zazu.yaml) as the parent for new branches rather than `develop`

The following is output if there is no `develop` branch
```
Checking out develop...
Traceback (most recent call last):
  File "/usr/local/bin/zazu", line 11, in <module>
    sys.exit(cli())
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/zazu/dev/commands.py", line 161, in start
    ctx.obj.repo.heads.develop.checkout()
  File "/usr/local/lib/python2.7/site-packages/git/util.py", line 889, in __getattr__
    return list.__getattribute__(self, attr)
AttributeError: 'IterableList' object has no attribute 'develop'
```

**Comment by stopthatcow** [comment]
related to #95
