### ISSUE TITLE
zazu dev status does not support empty JIRA description

### ISSUE THREAD

**Issue by moorepatrick** [stopthatcow/zazu#22]
If a JIRA issue does not have a description,  `zazu dev status` throws the following

```
❯❯❯ zazu dev status
Ticket info:
Traceback (most recent call last):
  File "/usr/local/bin/zazu", line 11, in <module>
    load_entry_point('zazu==0.0.0.dev0', 'console_scripts', 'zazu')()
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/zazu/dev/commands.py", line 215, in status
    issue = issue_future.result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/_base.py", line 429, in result
    return self.__get_result()
  File "/usr/local/lib/python2.7/site-packages/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/usr/local/lib/python2.7/site-packages/zazu/plugins/jira_issue_tracker.py", line 53, in issue
    ret.fields.description = ret.fields.description.split('\n\n----')[0]
AttributeError: 'NoneType' object has no attribute 'split' 
```

System Information:
macOS 10.12.4
Python 2.7.13 (default, Feb  9 2017, 11:38:19)
pip 9.0.1 from /usr/local/lib/python2.7/site-packages (python 2.7)
Zazu installed via readme instructions 04/17/17 from `develop` branch

**Comment by stopthatcow** [comment]
See #25 for fix
