### ISSUE TITLE
Git error when committing and auto-styling

### ISSUE THREAD

**Issue by stopthatcow** [stopthatcow/zazu#85]
[ OK  ] (clang-format) src/object_pool_allocator.hpp
fatal: Unable to create '/Users/nicholas/Development/switchboard/.git/index.lock': File exists.

Another git process seems to be running in this repository, e.g.
an editor opened by 'git commit'. Please make sure all processes
are terminated then try again. If it still fails, a git process
may have crashed in this repository earlier:
remove the file manually to continue.
Traceback (most recent call last):
  File "/usr/local/bin/zazu", line 11, in <module>
    sys.exit(cli())
  File "/Library/Python/2.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/Library/Python/2.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Library/Python/2.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Library/Python/2.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/Library/Python/2.7/site-packages/zazu/style.py", line 111, in style
    for f, violation in checked_files:
  File "/Library/Python/2.7/site-packages/zazu/util.py", line 121, in dispatch
    yield future.result()
  File "/Library/Python/2.7/site-packages/concurrent/futures/_base.py", line 422, in result
    return self.__get_result()
  File "/Library/Python/2.7/site-packages/concurrent/futures/thread.py", line 62, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/Library/Python/2.7/site-packages/zazu/style.py", line 72, in style_file
    write_fn(path, input_string, styled_string)
  File "/Library/Python/2.7/site-packages/zazu/style.py", line 45, in stage_patch
    zazu.util.check_output(['git', 'add', path])
  File "/Library/Python/2.7/site-packages/zazu/util.py", line 54, in check_output
    return subprocess.check_output(*args, **kwargs)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['git', 'add', u'src/hash_map_test.cpp']' returned non-zero exit status 128

This could be concurrency related.

**Comment by stopthatcow** [comment]
Duplicate of #86
